// Single source of truth for the test file list.
// Shared by scripts/run-tests.js (safe mode) and scripts/run-integration-tests.js
// (opt-in). Keep sorted roughly by priority / phase.

module.exports = [
  'tests/outreach-threads.test.js',
  'tests/gmail-guard.test.js',
  'tests/inbox-triage-self-mail.test.js',
  'tests/workspace-context.test.js',
  'tests/workspace-stamping.test.js',
  'tests/workspace-end-to-end.test.js',
  'tests/workspace-tables-phase2c.test.js',
  'tests/orchestrator.test.js',
  'tests/installer.test.js',
  'tests/coding.test.js',
  'tests/content-studio.test.js',
  'tests/twilio-whatsapp.test.js',
  'tests/intent-classifier.test.js',
  'tests/scheduler.test.js',
  'tests/chat-history.test.js',
  'tests/document-handling.test.js',
  'tests/workflow-engine.test.js',
  'tests/workflow-engine-phase2.test.js',
  'tests/workflow-marketplace.test.js',
  'tests/image-generation.test.js',
  'tests/image-generation-no-key.test.js',
  'tests/youtube-search.test.js',
  'tests/youtube-trending-comment.test.js',
  'tests/folder-watch-trigger.test.js',
  'tests/speech-to-text.test.js',
  'tests/video-editing.test.js',
  'tests/approval-video-preview.test.js',
  'tests/youtube-upload.test.js',
  'tests/analytics.test.js',
  'tests/self-prompting.test.js',
  'tests/guidance-skills.test.js',
  'tests/browser-extension-api.test.js',
  'tests/mcp-discovery.test.js',
  'tests/connector-detection.test.js',
  'tests/mcp-client.test.js',
  'tests/mcp-tool-safety.test.js',
  'tests/cli-detection.test.js',
  'tests/api-connector.test.js',
  'tests/cli-import.test.js',
  'tests/coding-agent-narration.test.js',
  'tests/chat-live-narration.test.js',
  'tests/job-verification.test.js',
  'tests/outreach-pipeline.test.js',
  'tests/response-followup.test.js',
  'tests/scheduling.test.js',
  'tests/outreach-automation.test.js',
  'tests/job-lead-gen-integration.test.js',
  // tests/telegram-integration.test.js intentionally omitted - referenced
  // by the old chain but has never existed on disk.
  'tests/auto-reply-safety.test.js',
  'tests/owner-notifications.test.js',
  'tests/business-profile-chat.test.js',
  'tests/computer-operator-search.test.js',
  'tests/computer-operator-openfile.test.js',
  'tests/computer-operator-openfolder.test.js',
  'tests/computer-operator-largefile.test.js',
  'tests/computer-operator-oldfile.test.js',
  'tests/computer-operator-duplicates.test.js',
  'tests/computer-operator-recyclebin.test.js',
  'tests/briefing-report.test.js',
  'tests/briefing-dashboard-articles.test.js',
  'tests/dashboard-stats.test.js',
];
